/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ygnynbxodtuqyufrahnp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbnluYnhvZHR1cXl1ZnJhaG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDcwNjEsImV4cCI6MjA3ODUyMzA2MX0.8FTe8eA3Hrhsy4fPZ1WjDhzt-b2jFJp-ZznToDzH-LA"